### ISSUE TITLE
Right click on Trayicon minimize window

### ISSUE THREAD

**Issue by cesar19004** [keshavbhatt/whatsie#47]
**Expected behavior**
- The app should only be shown or hidden when tray icon receives a left click
- Right click on the tray icon should only show the context menu and not modify the state of the app

**Obtained behavior**
- Right click on tray icon when the window has focus, hides the app and doesn't show the context menu
- Right click on tray icon when the window does NOT have focus, hides the app and shows the context menu
- Right click on tray icon when the app is hidden, shows the app and the context menu does not appear

**Comment by keshavbhatt** [comment]
> * The app should only be shown or hidden when the tray icon receives a left click

This behavior is customizable, see in the settings section of the application.
Even with all that, I am not able to guarantee if it will behave similarly on every Linux Desktop environment. Since they have their own specifications about the usage of system trays.

Can you please mention your Desktop environment so I can give it try in near future? That will be helpful.
Thank you.

**Comment by cesar19004** [comment]
> This behavior is customizable, see in the settings section of the application. 

There is only the following option
![image](https://user-images.githubusercontent.com/43949299/176327558-83c2b818-c752-4650-9ca7-1f3fc7b5a937.png)


> Can you please mention your Desktop environment so I can give it try in near future? That will be helpful. Thank you.

- WhatSie: v4.4 from snap
- OS: Ubuntu 22.04 LTS
- DE: GNOME 42.2

Thanks for your help :)

**Comment by shakaran** [comment]
@cesar19004, the maintained fork **Whatly** has a "minimise on tray-icon click" option in Settings, so a click on the tray icon can minimise or restore the window as you prefer. https://github.com/shakaran/whatly
