### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by erayerdin** [keshavbhatt/whatsie#71]
Today, I've seen Whatsie to occupy 10 gigs of RAM. I killed the process. I restarted it and then I got 5 gigs after 20 minutes of usage.

Something is causing the memory to leak.

---

# Environment

 - Fedora 36
 - Snap

**Comment by keshavbhatt** [comment]
I will check. Can you provide the debug info from about section of app?

**Comment by erayerdin** [comment]
@keshavbhatt 

`whatsie -b` spits out below:

```plain
Gtk-Message: 12:56:41.578: Failed to load module "colorreload-gtk-module"
Gtk-Message: 12:56:41.578: Failed to load module "appmenu-gtk-module"
Feature rich WhatsApp web client based on Qt WebEngine 
 version: 4.8, branch: main, commit: d03e9fc, built_at: 2022-08-30T15:43:06UTC
```

As for runtime logs, I have logged out and logged back in and problem solved itself. If I ever have it again, I will provide it.

BTW, where is "about" section? Whatsie does not have any native menu, so I couldn't find it.

**Comment by keshavbhatt** [comment]
Whatsie have system tray support if your desktop have a system tray, which has a context menu with lots of entries. If you dont have system tray on your desktop you can access them from Desktop actions, right click on whatsie icon in your taskbar to access few options.

**Comment by keshavbhatt** [comment]
Whatsie have system tray support if your desktop have a system tray, which has a context menu with lots of entries. If you dont have system tray on your desktop you can access them from Desktop actions, right click on whatsie icon in your taskbar to access few options.

**Comment by erayerdin** [comment]
"About > Show Debug Info" displays below:

```plain
WhatSie
Version: 4.8
Source Branch: main
Commit Hash: d03e9fc
Build Datetime: 2022-08-30T15:43:06UTC
Qt Runtime Version: 5.15.4
Qt Compiled Version: 5.15.4
System: Ubuntu Core 20
Architecture: x86_64
```

Also, Whatsie stucks on "Organizing Messages" as seen below:

![image](https://user-images.githubusercontent.com/2399084/187781529-ed0c9046-ab1c-4c82-9c21-5c9160f59275.png)

This might be related to #72 because I get the same high CPU usages and it leaks memory after a while up to 10 gigs.

**Comment by keshavbhatt** [comment]
Yeah the problem of loading sticking at organizing messages is known. Strange part is, the issue is not reproducible and I am not able to detect what is causing it. Memory leaks is happen in the webengine side since the page is stuck doing something that is not progressing. I am not doing anything from the code its just a simple page load event. So, i have no control atm on it. I will try to debug it when i will get a chance to see it on my install. 

Thanks for reporting.

**Comment by keshavbhatt** [comment]
Also, It seems like a known problem with whatsapp web since they rolled out new version, a quick google search returns lot of results. Anyway i will try my best to fix it on Whatsie.

**Comment by keshavbhatt** [comment]
We will track this issue here https://github.com/keshavbhatt/whatsie/issues/58

**Comment by shakaran** [comment]
@erayerdin — for folks landing here about RAM: the maintained fork **Whatly** now ships V8 *optimize-for-size* by default, plus a JS-heap limit and cache controls in Settings → Performance, which brings the idle QtWebEngine footprint down noticeably. It's largely the cost of the full Chromium engine rather than a true leak, but these knobs genuinely help. https://github.com/shakaran/whatly
