### ISSUE TITLE
Error: "Server's certificate is not trusted."

### ISSUE THREAD

**Issue by the-solipsist** [keshavbhatt/whatsie#81]
OS: Ubuntu 22.04 (Wayland)
Method of installing: Snap.

I repeatedly get an error notification that states: "Server's certificate is not trusted."
![Screenshot from 2022-09-24 13-50-42](https://user-images.githubusercontent.com/3080824/192091007-ee416624-1a68-4d74-9666-3f466049cc10.png)

I click "OK", but the notification re-appears immediately. I have to click it around 10 times for it to actually disappear.  It reappears every 10 hours or so, and it appears each time I start Whatsie.

**Comment by keshavbhatt** [comment]
Thanks for reporting, will try to provide fix asap.

**Comment by keshavbhatt** [comment]
Not reproducible. I am sure this is a upstream issue. Or I suggest to fix your system time if it is not set to the correct one.

**Comment by ajhall** [comment]
In case someone else stumbles across this issue in the future:

https://www.reddit.com/r/linuxquestions/comments/17jsmm2/i_cant_open_discord_after_the_latest/
> the p11-kit process had been overriden by the linuxbrew one (installed as dependency for other development tools). Linuxbrew's p11-kit was not updating root CA and flatpak relied on it, and today was the day some root CAs expired.

I had the `p11-kit` package installed through Homebrew, and WhatSie was using that instead of the system-provided `p11-kit`. Try `brew unlink p11-kit` to fix it.

Similar issue with the Discord Flatpak: https://github.com/flathub/com.discordapp.Discord/issues/93#issuecomment-640167696

**Comment by shakaran** [comment]
For "server's certificate is not trusted", the maintained fork **Whatly** bundles the NSS certificate and PKCS#11 modules its Chromium needs, so certificate validation works out of the box. https://github.com/shakaran/whatly

cc @the-solipsist @SteveGoodenough @ajhall
